import Head from "next/head";
import BoardEmpty from "../components/UI/BoardEmpty";
import kanbanData from "../public/data.json";
import { useSelector } from "react-redux";
import { selectMenuIsVisible } from "../store/uiSlice";
import { selectCurrentBoard } from "../store/boardSlice";

export default function Home() {
  const menuOpen = useSelector(selectMenuIsVisible);
  const currentBoardId = useSelector(selectCurrentBoard);
  const boardData = kanbanData.boards.find(
    (board) => board.id === currentBoardId
  );

  return (
    <div
      className={`${
        menuOpen
          ? `translate-x-0 md:w-[calc(100vw_-_260px)] lg:w-[calc(100vw_-_300px)]`
          : `md:-translate-x-[260px] lg:-translate-x-[300px]`
      }   h-screen w-screen transition duration-100`}
    >
      <Head>
        <title>Kanban</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/assets/logo-mobile.svg' />
      </Head>

      <main className='h-full w-full overflow-scroll '>
        {kanbanData.boards.length === 0 && <BoardEmpty />}

        <div className='mx-4 mb-[70px] mt-[88px] flex space-x-6 md:mx-6 md:mt-[104px]'>
          {boardData.columns.map((item, i) => (
            <div key={i} className='w-[280px] flex-none'>
              <div className='flex'>
                <div className='mr-3 h-[15px] w-[15px] rounded-full bg-[#49C4E5]' />
                <h4 className='uppercase'>
                  {item.name} ({item.tasks.length})
                </h4>
              </div>
              <ul className='mt-6 space-y-5'>
                {item.tasks.map((task, j) => {
                  var completedTasks = 0;
                  task.subtasks.filter((item) => {
                    if (item.isCompleted) {
                      completedTasks++;
                    }
                  });

                  return (
                    <div
                      key={j}
                      className='rounded-lg bg-white px-4 py-6 shadow-md dark:bg-grey_dark'
                    >
                      <h3>{task.title}</h3>
                      <p className='bodyM mt-2 text-grey_medium'>
                        {completedTasks} of {task.subtasks.length} subtasks
                      </p>
                    </div>
                  );
                })}
              </ul>
            </div>
          ))}
          <div className='mt-[39px] h-auto w-[296px] flex-none md:w-[304px] '>
            <div className='grid h-full w-[280px] items-center rounded-md bg-[#E9EFFA] text-center dark:bg-grey_dark'>
              <h1 className='cursor-pointer text-grey_medium hover:text-purple_main'>
                + New Column
              </h1>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
